group: mathvista
task:
  - mathvista_testmini
  - mathvista_test
metadata:
  version: 0.0
  # gpt_eval_model_name: "gpt-4-0613"
  # gpt_eval_model_name: "gpt-4o-2024-05-13"
  gpt_eval_model_name: "gpt-4-0125-preview"
  quick_extract: false